CREATE TABLE job_descriptor (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    source_type VARCHAR(32) NOT NULL,
    bean_name VARCHAR(255),
    method_or_class VARCHAR(255),
    trigger_info VARCHAR(512),
    discovered_at TIMESTAMP NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE job_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP NOT NULL,
    finished_at TIMESTAMP,
    duration_ms BIGINT,
    error_message VARCHAR(4096),
    trigger_source VARCHAR(32) NOT NULL,
    CONSTRAINT fk_job_execution_job FOREIGN KEY (job_id) REFERENCES job_descriptor(id)
);

CREATE INDEX idx_job_execution_job_started ON job_execution(job_id, started_at DESC);

CREATE TABLE job_next_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL UNIQUE,
    calculated_next_run_at TIMESTAMP,
    CONSTRAINT fk_job_next_run_job FOREIGN KEY (job_id) REFERENCES job_descriptor(id)
);
